name: Increment git tag
on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Increment
        uses: wai-calvin/ghas-bootcamp-test/.github/actions/action.yml
