name: Increment git tag
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: git tag
        run: git tag

      - name: Set Output
        id: tags
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*}

      - name: Check Tag 
        env:
          RELEASE_VERSION: ${{ steps.tags.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      - name: Set Tag 
        id: patch
        run: |
          re="/(\d+)\D*\z"
          tag=${{ steps.vars.outputs.tag }}
          if 
            [[ $tag =~ $re ]]; 
            then echo ${BASH_REMATCH[1]}; 
          fi


