name: Increment git tag
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: git tag
        run: git tag

      - name: gitref 
        run: echo ${GITHUB_REF}

      - name: Set Output
        id: tags
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/*/}

      - name: Check Tag 
        env:
          RELEASE_VERSION: ${{ steps.tags.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.tags.outputs.tag }}

      - name: Set Tag 
        id: patch
        run: |
          re="/([0-9]+)\D*\z"
          tag="${{ steps.tags.outputs.tag }}"
          if 
            [[ $tag =~ $re ]]; 
            then echo ${BASH_REMATCH[1]}; 
          fi


