name: Will this tflint

on:
  push:
    branches:
      - main

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: hashicorp/setup-terraform@v2
      - name: lint
        run: tflint -h

